# Generated by Django 4.0.3 on 2023-02-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Business', 'Business'), ('Individual', 'Individual')], max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('account_manager', models.CharField(max_length=150)),
                ('date_blacklisted', models.DateField()),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
    ]
